---
name: _build

on:
  workflow_call:
    inputs:
      docker_image:
        description: Docker image
        type: string
        required: true
      build_matrix:
        description: Build matrix for multi target builds
        type: string
        required: true

jobs:
  build:
    runs-on:
      group: GHA-Video-Stg-SelfHosted-RG
      labels: [self-hosted, video-stg-u2204-x64-large-od-ephem]
    strategy:
      fail-fast: false
      matrix:
        build_matrix: ${{ fromJson(inputs.build_matrix) }}

    steps:
      - name: Build docker image
        id: docker_build
        uses: qualcomm-linux-stg/video-driver/.github/actions/build_docker_image@video.qclinux.0.0

      - uses: actions/checkout@v4

      - name: Build ${{ matrix.build_matrix.machine }}
        uses: qualcomm-linux-stg/video-driver/.github/actions/build@video.qclinux.0.0
        with:
          docker_image: ${{ steps.docker_build.outputs.image_name }}
          kas_file: ${{ matrix.build_matrix.kas_file }}
          build_command: "bitbake qcom-multimedia-proprietary-image"
