name: Post Merge Weekly
description: |
  Runs post-merge CI for the video-driver repository on a weekly schedule.
  Reuses loading, build and test workflows.

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  loading:
    uses: qualcomm-linux/video-driver/.github/workflows/loading.yml@video.qclinux.0.0
    secrets: inherit

  build:
    needs: loading
    uses: qualcomm-linux/video-driver/.github/workflows/sync-and-build.yml@video.qclinux.0.0
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}

  lava-test:
    needs: [loading, build]
    uses: qualcomm-linux/video-driver/.github/workflows/test.yml@video.qclinux.0.0
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      full_matrix: ${{ needs.loading.outputs.full_matrix }}