---
name: pre_merge
run-name: Pre Merge Workflow
on:
  workflow_dispatch:
  pull_request_target: # requiring access to base repo
    types: [opened, synchronize, reopened]
    branches:
      - video.qclinux.0.0

jobs:
  loading:
    uses: hasiburr-qti/video-driver/.github/workflows/loading.yml@test-mount-2
    secrets: inherit

  build:
    needs: loading
    uses: hasiburr-qti/video-driver/.github/workflows/build.yml@test-mount-2
    secrets: inherit
    with:
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
  
  process_image:
    needs: [loading, build]
    uses: hasiburr-qti/video-driver/.github/workflows/process_image.yml@test-mount-2
    with:
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
