---
name: pre_merge
run-name: Pre Merge Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - test-workflow

jobs:
  loading:
    uses: qualcomm-linux-stg/video-driver/.github/workflows/loading.yml@test-workflow
    secrets: inherit

  build:
    needs: loading
    uses: qualcomm-linux-stg/video-driver/.github/workflows/build.yml@test-workflow
    secrets: inherit
    with:
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      docker_image: video-image:ver.1.0
